llm:
  model_name: "gpt-4o-mini"
  temperature: 0.1
  chunk_size: 600
  max_attempts: 3

audio:
  min_duration: 5.0
  max_gap: 20.0
  download_dir: "podcasts"

log_level: "INFO"

# Message broker settings
message_broker:
  type: "mqtt"  # Options: "mqtt", "in_memory"
  mqtt:
    # Host and credentials are loaded from secrets.json
    host: null
    port: null
    username: null
    password: null
    client_id: null

# Web server settings
web_server:
  host: "localhost"
  port: 8080
  use_https: false 